### PR TITLE
OBPIH-5220 Send more information to New Relic, as recommended by New Relic

### PR DESCRIPTION
**Pull request by mdpearson**

### CODE REVIEW

**Comment by jmiranda** [comment]
@mdpearson Can you provide some more details (in the ticket) to help me understand what this does and why we need/want it? Since we're using NewRelic I'm all for anything that provides more details on the APM side of things. But other than the "transaction name" component I don't really have a basis for judging this change. In addition, do we need to consider making this configurable? For example, if someone is hosting the application on a LAN without internet will this have any negative impact?

**Comment by mdpearson** [comment]
I'll check with New Relic themselves about this as part of https://pihemr.atlassian.net/browse/OBS-1454

**Comment by mdpearson** [comment]
@jmiranda when we were looking at the dashboards today with New Relic -- this code was running on the host we were looking at. I don't think it necessarily needs to go out with the next release if there's a code freeze, but I did want to bring it to your attention.

**Comment by jmiranda** [comment]
@mdpearson As mentioned on the tech debt call I thought we were missing tags from the React page, but it looks like i was mistaken. The grails-template.html file (under src/assets) is actually using the main.gsp template so we should be ok there.

**Comment by mdpearson** [comment]
@jmiranda any other edits required for this PR?

**Review by jmiranda — APPROVED** [review]
@mdpearson Nope. LGTM.

**Comment by jmiranda** [comment]
@awalkowiak If you feel comfortable with these changes can you merge them with the other hotfix issues.

**Pull request merged**
