### PR TITLE
Merge release-0.8.0 branch into develop

### PR DESCRIPTION
**Pull request by jmiranda**

### CODE REVIEW

**Comment by jmiranda** [comment]
@pmuchowski Can you fix the conflicts in package-lock.json and webpack.config.js so that I can merge all changes from the release branch into develop? The changelog.xml is easy (just include both changesets).

**Comment by jmiranda** [comment]
@pmuchowski I don't understand why this happened though so let's discuss on Slack tomorrow. And what kind of merge is required: commit merge or squash & merge?

**Comment by pmuchowski** [comment]
@jmiranda I think this will require commit merge

**Comment by pmuchowski** [comment]
@jmiranda I created new PR to add release changes to develop: https://github.com/openboxes/openboxes/pull/613
I think we should close this PR and revert the changes added to release-0.8.0

**Pull request closed without merging**
