### PR TITLE
OBGM-468 Fix no transaction for product type update and delete methods

### PR DESCRIPTION
**Pull request by kchelstowski**
Katarzyna has asked me to fix also update and delete methods in this ticket, so those are the changes to include them.

### CODE REVIEW

**Review by alannadolny — APPROVED** [review]

**Review by drodzewicz — CHANGES_REQUESTED** [review]
Looking at the changes you have made reminded me of what Justin mentioned not too long ago about not wanting to create separate domain-based services.
Although it is not the exact case here, I think we can avoid implementing simple `get()` `delete()` etc... actions in services and instead use a generic approach like `GenericApiService`.
Both **delete** and **get** are already implemented there

**Comment by drodzewicz** [comment]
Alternatively, there is also this approach of creating an abstract class with generic actions and extending some other services with this abstract class like it is shown in the examples of [this little article](https://ultimate.systems/web/blog/generic-controllers-and-services-in-spring-boot-java). 
Both approaches are in my opinion good and it is just a matter of preference, but either way, it definitely reduces the amount of redundant code that we have to implement and keeps the codebase a little bit more DRY.

**Comment by kchelstowski** [comment]
@drodzewicz as for `get` I can agree, but I don't like the delete method of `genericApiService`. It does an unnecessary additional fetch to get the object and then to delete it, so I'd have N+1 queries there.

**Review by drodzewicz — APPROVED** [review]

**Review by awalkowiak — APPROVED** [review]

**Review by jmiranda — APPROVED** [review]
LGTM. 

By the way, this is one of those scaffolded CRUD controllers that I'd prefer to be @Transactional until we figure out where these methods should go i.e. probably ProductService. But since this one snuck in, we can grandfather it in and refactor later if we choose.

**Pull request merged**
