### PR TITLE
OBPIH-3215 Receiving design update

### PR DESCRIPTION
**Pull request by bamoure**
@awalkowiak I have an issue on this ticket regarding what you mentioned on Slack yesterday: when the disabled condition is set in `getDynamicAttr` the field does not get disabled even if the condition is true. Do you know why this is the case?

For example on the PartialReceivingPage, the checkboxes get disabled as well as the top Bin Location select (where the disabled is set directly), but not the other fields.

### CODE REVIEW

**Comment by awalkowiak** [comment]
@bamoure this is because my changes fixing it were not yet merged.

**Comment by bamoure** [comment]
@awalkowiak So will it work automatically once your fix is merge? Or is there anything I need to change here?

**Comment by awalkowiak** [comment]
@bamoure I merged mine, you can rebase this pr and check if everything works properly.

**Comment by awalkowiak** [comment]
@bamoure in this case it is better to do the rebase locally and force push to the branch, now I have to go through my code during the review (note for future).

**Review by awalkowiak — APPROVED** [review]

**Pull request merged**
