### PR TITLE
Merge hotfixes back to develop.

### PR DESCRIPTION
**Pull request by mdpearson**
Hey Justin, it looks like like three hotfix commits aren't in develop. This PR is a merge of master into develop, followed by a rebase, yielding 3 commits. But we could do a regular merge if you want to preserve the merge history. What's your preferred way to sync the changes?

### CODE REVIEW

**Comment by jmiranda** [comment]
Yeah I usually merge master to develop as part of the "cleanup" process https://docs.openboxes.com/en/latest/developer-guide/release/cleanup/. I just tried to do it myself but got tripped up by the conflicts. I'll make another attempt tomorrow.

**Comment by mdpearson** [comment]
> Yeah I usually merge master to develop as part of the "cleanup" process https://docs.openboxes.com/en/latest/developer-guide/release/cleanup/. I just tried to do it myself but got tripped up by the conflicts. I'll make another attempt tomorrow.

This is something I'd be happy to do, but I cannot push to protected branches.

**Comment by jmiranda** [comment]
Thanks. It feels like there's more to this than the PR is taking into account. I tried to do the merge again tonight, but encountered the issue in the video. 
https://watch.screencastify.com/v/x3REluv6ftCww4ycoAu1

Since I don't feel comfortable resolving that, I'll to leave it up to @MagdaToczek and @awalkowiak.

Can you guys take a look at this? I don't know whether Artur's addition of the location argument needs to be included in Magda's hotfix.

image

**Comment by MagdaToczek** [comment]
I'll wait with it till @awalkowiak be back.

**Comment by awalkowiak** [comment]
@jmiranda ugh, yeah I forgot about that one. I'll recheck it tomorrow morning after hotfix3 release and I'll merge it.

**Review by awalkowiak — APPROVED** [review]

**Pull request merged**
