### PR TITLE
OBPIH-4937 Change string in filter search field for PO list

### PR DESCRIPTION
**Pull request by drodzewicz**

### CODE REVIEW

**Review by kchelstowski — APPROVED** [review]
Out of curiosity - have you changed all those files or you have changed only English one and the rest of them were changed automatically somehow?

**Comment by drodzewicz** [comment]
> Out of curiosity - have you changed all those files or you have changed only English one and the rest of them were changed automatically somehow?

I manually changed those files

**Comment by kchelstowski** [comment]
@drodzewicz I believe you didn't have to add it to each file, since crowdin would add them by itself as soon as your PR is merged

**Comment by drodzewicz** [comment]
> @drodzewicz I believe you didn't have to add it to each file, since crowdin would add them by itself as soon as your PR is merged

didn't know that.
Let me revert changes to other files then

**Comment by kchelstowski** [comment]
@drodzewicz I would actually stick with it, so we would know what happens in that case, if you update other files by yourself. The more experience and knowledge with have with some others cases about crowdin, the better

**Review by awalkowiak — APPROVED** [review]

**Pull request merged**
