### PR TITLE
OBDS-33: Document installation steps for Grails 3 version of OB

### PR DESCRIPTION
**Pull request by kkaczmarczyk**

### CODE REVIEW

**Comment by jmiranda** [comment]
This actually needs to go to master (or develop then master during a release) in order to show up in the docs. I'm going to close this ticket but I need some more time to think about how this should work.

**Comment by jmiranda** [comment]
@kkaczmarczyk I found an issue that I'm not sure how to deal with. Any thoughts?

image

**Comment by jmiranda** [comment]
The other issue is that the grails branch has an older version of the docs theme so I may want to add it to master / develop and have it migrated to the grails branch in an upcoming rebase.

image

**Comment by kkaczmarczyk** [comment]
@jmiranda I see, would you like me to make the PR to develop? About the sections bug - when does it happen? After clicking on which section? And would the new theme fix that?

**Comment by jmiranda** [comment]
@kkaczmarczyk 
> I see, would you like me to make the PR to develop? 
Yeah why don't you change the PR to target develop. 

> About the sections bug - when does it happen? After clicking on which section? 
Just loading the docs index page triggers it. It's weird. I doubt it has anything to do with your changes but I've never seen it before.

> And would the new theme fix that?
Not sure but we'll find out after you rebase to develop.

**Comment by kkaczmarczyk** [comment]
@jmiranda I've created the PR to develop at #2399. I am closing this PR and removing the branch.

**Pull request closed without merging**
