### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by jmiranda**

### CODE REVIEW

**Comment by mworinger** [comment]
@awalkowiak @jmiranda @kchelstowski This PR is verified and can be merged.

**Comment by mworinger** [comment]
@awalkowiak @jmiranda @kchelstowski New changes are also verified and can be merged.

**Comment by mworinger** [comment]
@kchelstowski @jmiranda @jmiranda The last 6 commits are verified and all good too. (The scare of Spanish translations submitted onto French is now rectified.)

**Comment by jmiranda** [comment]
@awalkowiak Do you usually squash these?

**Comment by awalkowiak** [comment]
@jmiranda yes, I always squash these PRs

**Pull request merged**
