### PR TITLE
OBS-461 Set transactionNumber anytime new transaction is created

### PR DESCRIPTION
**Pull request by DominikaHatala**

### CODE REVIEW

**Review by awalkowiak — COMMENTED** [review]
@DominikaHatala how about a few transactions that are created in `IventoryController` (in `saveInventoryChanges` and `saveTransaction`) and in `InventoryItemController` (in `saveInventoryItem` and `saveTransactionEntry`)? Do we need it there too?

**Comment by DominikaHatala** [comment]
@awalkowiak **saveInventoryChanges**, **saveInventoryItem** and **saveTransactionEntry** are not used anywhere(at least I couldn't find any usage either in code or while testing all places with inventory transactions i napplications) and **saveTransaction** is using existing transaction(with transactionNumber already set) so I don't think

**Comment by DominikaHatala** [comment]
@jmiranda Can I help you somehow with any work in this one?

**Comment by jmiranda** [comment]
@DominikaHatala This one'll just go to develop i.e. the next release. If we end up needing it sooner we can create a hotfix.

**Comment by awalkowiak** [comment]
@jmiranda seems like this one is ready to be merged. I'll merge it on Monday when Katarzyna will be back in the office.

**Pull request merged**
