### PR TITLE
OBAM-130 Migrate OrderTypeCode into OrderType

### PR DESCRIPTION
**Pull request by awalkowiak**
@jmiranda I was not sure if the old OrderTypeCode should stay for now too, or should it be removed (in these changes I removed it). Take a look and let me know if there is anything missing. If that's all, then I'll refactor the existing usage of OrderTypeCode into OrderType. Unless you want to keep OrderTypeCode for now, then I'll re-add this property and I'll remove the changeset that removes this column from the table.

### CODE REVIEW

**Comment by jmiranda** [comment]
Ok I'll take a look later tonight or tomorrow. But basically OrderTypeCode moves to OrderType and OrderType gets populated with the OrderType associated the old orderTypeCode.

**Review by jmiranda — APPROVED** [review]
looks good to me

**Comment by jmiranda** [comment]
@jmiranda DO NOT MERGE. DO NOT MERGE. We need to wait until after the release branch gets created.

**Comment by awalkowiak** [comment]
@jmiranda I pushed the remaining refactor. Review it, please.

**Comment by jmiranda** [comment]
@awalkowiak can you fix the conflict with the database migration.

**Comment by awalkowiak** [comment]
@jmiranda done

**Review by jmiranda — APPROVED** [review]
It's not a matter of if there'll be a regression, but when.

**Comment by jmiranda** [comment]
Merge after release branch is created.

**Comment by jmiranda** [comment]
@awalkowiak I'll let you merge this yourself tomorrow because it would be good if you were around and clear-headed in case this introduces any showstopper bugs on OBDEV.

**Pull request merged**
