### PR TITLE
Global search fix

### PR DESCRIPTION
**Pull request by awalkowiak**
https://tickets.pih-emr.org/browse/OBPIH-1266

### CODE REVIEW

**Comment by awalkowiak** [comment]
@jmiranda by default filterOptions takes options and filters them by searchTerm (https://github.com/HubSpot/react-select-plus#filtering-large-lists). This "options => options" function takes options as parameter and returns options as they came in.

**Comment by jmiranda** [comment]
Ah ok. That makes way more sense. I was starting to think the default behavior for that select component was "f*ck it, ignore the response".

**Comment by awalkowiak** [comment]
@jmiranda No, it was filtering the response additionally. But what you filtered in "smart way" on backend, this feature filtered those options in "dumb way" (for example from your gif, it tried to filter results by "ibu 200", looking for this string)

**Comment by jmiranda** [comment]
Yeah exactly. Glad it was an easy fix. And for the record, my questions here are just to help me get a better understanding of React.

**Pull request merged**
