### PR TITLE
OBPIH-2874 Dashboard: Inventory Summary by Product

### PR DESCRIPTION
**Pull request by bamoure**

### CODE REVIEW

**Comment by jmiranda** [comment]
Sorry for the delay @bamoure. LGTM.

@awalkowiak Can you take a look tomorrow?

**Comment by bamoure** [comment]
@jmiranda Actually can we hold off on merging this branch? It will be mostly rewritten by the general dashboard config one

**Comment by jmiranda** [comment]
@bamoure Yeah sure.

**Comment by jmiranda** [comment]
@bamoure Should we close this PR and remove the branch?

**Pull request closed without merging**
