### PR TITLE
OBPIH-796 Create COD for Rwanda

### PR DESCRIPTION
**Pull request by DominikaHatala**

### CODE REVIEW

**Comment by awalkowiak** [comment]
@DominikaHatala should this be available from other locations? Seems like there is no location checking for this document.

**Comment by jmiranda** [comment]
Marking as "do not merge" because it was not implemented using the document template feature.

**Comment by jmiranda** [comment]
@DominikaHatala It's the way the other COD document is implemented. See the download action on DocumentController. But now that I'm looking at the ticket requirements it seems they want this as an XLS. Which probably means neither approach would have been suitable.

**Comment by DominikaHatala** [comment]
@jmiranda Yes, they want is an XLS that's why I've done it this way. Kelsey says it looks good so should I refactor it somehow?

**Comment by jmiranda** [comment]
@DominikaHatala No, I'll merge it as-is. The problem is that this is a very PIH-specific document in a project that is trying to be organization agnostic. I'll add a ticket to refactor what I think needs to be done to make this less PIH-y.

**Pull request merged**
