### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by jmiranda**

### CODE REVIEW

**Comment by mworinger** [comment]
@awalkowiak @jmiranda @kchelstowski 
This crowdin PR can be merged partially (**!!!!**).
The changes in the following commits are valid translation changes I made: [2029ac5] [5731ec1] [5594752] [3dfb59d] [0de740d].
I **do not know** the reason for the 3 other commits, they don't correspond to any crowdin activity --> [ec112e5] [7e5ab6b] [9faeb39]

**Comment by kchelstowski** [comment]
@mworinger thanks for that update. Are you sure that e.g. this one: [ec112e5](https://github.com/openboxes/openboxes/commit/ec112e5122dcaef424447dd79490c13df570e715) doesn't correspond to any crowdin activity? It just translates from English to French.
I can see that this `default.monthly.label` has been added at 11.01.2023 to `messages.properties`, so was to `messages_fr.properties` with the English version.
If no one was translating that string and the others from this commit, I've no idea at the moment, who and how would translate that to French.

**Comment by mworinger** [comment]
@kchelstowski changes in [ec112e5] correspond to old crowdin activity:

- `default.monthly.label` is from 5 months ago
- `default.dataTable.show.label` is from 3 months ago
- `deliveryNote.comments.label` is from 4 months ago
- etc.

So do you understand why they are part of this PR? Haven't they been merged already?

Capture d’écran 2023-04-20 à 14 45 00
Capture d’écran 2023-04-20 à 14 46 33
Capture d’écran 2023-04-20 à 14 45 43

**Comment by kchelstowski** [comment]
@mworinger so do you say that e.g. `default.monthly.label` should have already been there for 5 months as "Par mois", but somehow isn't and crowdin wants to merge it now?
From what I can see it feels like it (the translation to "Par Mois") has never been merged, because last change in the French file of that string was as I said - 11.01.2023 (so that would be also counted as 5 months)

**Comment by mworinger** [comment]
@kchelstowski It must have been merged, because it's there both on obdev1 (develop) and obnav (master).
So we need to understand why crowdin is trying to re-merge it.
Capture d’écran 2023-04-20 à 18 38 15

**Comment by kchelstowski** [comment]
@mworinger the one that you have shown is on Consumption report - it doesn't use `default.monthly.label` there, but `consumption.monthly.label` which is correctly merged in French:
https://github.com/openboxes/openboxes/blob/080001ae50724ad97994dcd3cefe9b6bc120f0c6/grails-app/i18n/messages_fr.properties#L134

So we have two different labels with the same translation.

`default.monthly.label` is used on the Demand tab of product view page in the footer of the table:
Screenshot from 2023-04-20 19-25-33

Do you remind yourself translating this particular string in this place ever? If no, I maybe have an interesting discovery.

**Comment by mworinger** [comment]
@kchelstowski "Do you remind yourself translating this particular string in this place ever?" -- I think I have, but I can't give you a much more definite answer than that. Yesterday when I looked for the string in openboxes to write my previous comment, my intuition brought me to this page/tab first, before I checked the consumption report. so I'm guessing this intuition came from remembering that I translated this word there. :)

2 things I noticed that maybe you noticed already that could be helpful:

- There are only those 2 strings for "Monthly" present in openboxes. Both of them have a translation indicated as "5 months ago".
Capture d’écran 2023-04-21 à 10 51 20

- It seems like one is merged `consumption.monthly.label` and one is not `default.monthly.label` because in FR locale I see "Monthly" on the stock card demand tab, while in Acoli locale the translation "Par mois" is present
Capture d’écran 2023-04-21 à 10 58 35

**Comment by mworinger** [comment]
@kchelstowski 
5 new translations from 23 April are in [c0ec214](https://github.com/openboxes/openboxes/pull/3998/commits/c0ec214dad0db36acd4039a3e7c88b7fb9718cfa)
14 new translations from 24 April are in [48c615a](https://github.com/openboxes/openboxes/pull/3998/commits/48c615a4c49fae830ea37cc1203d4702abd43672)

other commits aren't related to my activity

**Comment by mworinger** [comment]
@awalkowiak @kchelstowski
If only the commits with a green tick ✅ will be merged, then yes, all the French commits with a green tick are valid.

Except that: There are 4 Portuguese commits with a green tick. Those are not coming from our activity.

I also noticed that the latest activity from today 12:37pm CET don't have a commit yet. That would be something weird to investigate if they don't come in shortly.
Capture d’écran 2023-04-26 à 20 18 54

**Comment by kchelstowski** [comment]
@mworinger thanks for the update. [8b27590](https://github.com/openboxes/openboxes/pull/3998/commits/8b275905e2fded431d5188986c9c09492d271c06) contains the two labels you've mentioned that "are not there yet".
BTW. If you wanna do a sanity check of "all changes", just go to the "Files changed" tab, so you can see all commits as one:
Screenshot from 2023-04-27 09-03-28

it's easier to follow all the changes then, instead of checking commit by commit especially when I was playing around with it, and removing/adding the same stuff for multiple times.
Let me know if now we have a green light to proceed

**Comment by mworinger** [comment]
the 2 latest commits are also expected. green light bis @awalkowiak

**Pull request merged**
