### PR TITLE
OBGM-301 Exception Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long

### PR DESCRIPTION
**Pull request by chetanmaharishi**
Please review my changes, 
Bug fixed for running app in Windows machine.

### CODE REVIEW

**Comment by awalkowiak** [comment]
@chetanmaharishi Are you sure this is targetting the proper branch?

**Comment by jmiranda** [comment]
@chetanmaharishi For OBGM tickets, we want pull requests to target the OBGM branch
```
feature/upgrade-to-grails-3.3.10
``` 
In addition, please include the ticket number and summary in your commit message. In this case the following would be fine:
```
OBGM-301 CreateProcess error=206, The filename or extension is too long
```

**Comment by chetanmaharishi** [comment]
OK i will take care of this in future.

**Review by jmiranda — COMMENTED** [review]
LGTM, just need to run it locally.

**Pull request merged**
