### PR TITLE
OBPIH-2880 Dashboard should be customizable by user

### PR DESCRIPTION
**Pull request by awalkowiak**

### CODE REVIEW

**Comment by awalkowiak** [comment]
@jmiranda I had to revert this PR because it broke the odbev. It was complaining about missing dashboard_config column (i guess this requires migration)

**Comment by jmiranda** [comment]
@awalkowiak Thanks.

**Comment by jmiranda** [comment]
@julienreliefapps @bamoure Can you handle this conflict? I could have sworn I saw the config endpoint still in the TableroController earlier during code review so I'm a little confused.

**Comment by bamoure** [comment]
@jmiranda I simply removed the TableroController as we don't need it anymore. In the PR to make the dashboard the landing page we removed the index, and in this one we moved the config to the APITableroController

**Comment by jmiranda** [comment]
@bamoure Sounds good. I think I was looking at an older copy of the code on my laptop.

**Pull request merged**
