### PR TITLE
Obgm 58 database migrations

### PR DESCRIPTION
**Pull request by jmiranda**
Need to ensure that executing database migrations over existing databases works properly before committing (OBGM-79).

Do not merge without squashing first.

### CODE REVIEW

**Comment by jmiranda** [comment]
@awalkowiak Take a look at BootStrap.groovy, build.gradle, grails-template.html when you get a chance. The rest of the PR is just reorganizing the database migration changelogs.

**Comment by awalkowiak** [comment]
@jmiranda minor conflict in build.gradle snuck in

**Comment by jmiranda** [comment]
@awalkowiak Seems the only option here is to the force pushed version of the `feature/upgrade-to-grails-3.3.10` branch. Then I can create a new feature branch `OBGM-58-second-try` off of that branch and cherry pick changes from `OBGM-58-database-migrations` into 

The part i don't know is how do i `feature/upgrade-to-grails.3.3.10`. Do I need to fetch / pull and then do a `git reset --hard`? 
 
I used this SO answer as a reference https://stackoverflow.com/a/18516367

**Comment by jmiranda** [comment]
I'm an idiot. This was much easier than I realized. I deleted the branch 

Check the status of the branch ... ewwww yeah
```
$ git status
On branch feature/upgrade-to-grails-3.3.10
Your branch and 'origin/feature/upgrade-to-grails-3.3.10' have diverged,
and have 123 and 216 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
```
Delete the local base branch
```
$ git branch feature/upgrade-to-grails-3.3.10 -D
Deleted branch feature/upgrade-to-grails-3.3.10 (was c78c525cd).
```
Checkout the base branch again
```
$ git checkout -b feature/upgrade-to-grails-3.3.10 origin/feature/upgrade-to-grails-3.3.10 
Branch 'feature/upgrade-to-grails-3.3.10' set up to track remote branch 'feature/upgrade-to-grails-3.3.10' from 'origin'.
Switched to a new branch 'feature/upgrade-to-grails-3.3.10'
```
Create a new feature branch off the newly checked out base branch
```
$ git branch -b OBGM-database-migrations-new
Switched to a new branch 'OBGM-58-database-migrations-new'
```
Cherry pick changes from the old OBGM-database-migrations branch
```
$ git cherry-pick 6077ea39ef34d7d4c9f43af2f0708512d15fa8e2
$ git cherry-pick 17bc0a57e5c3a541aa3c355d16ed902876998435
$ git cherry-pick e1b7ec7cdc3937b10c16a49c65aeff661e1e01ae
$ git cherry-pick 996ef5dde8ea192933795c46278d8a2523d1d480
$ git cherry-pick 1f47094b03b0e634e608b2df6cde85cd82fe701d
$ git cherry-pick e362a2900dcd648722f31ce0a820f1d5bfaab966
$ git cherry-pick 2b0c12fff75f1a56bcec00b969ebcb8955fcb3aa
$ git cherry-pick bf765ac14d2050dafd9f5dce8091ef623243cf93
$ git cherry-pick 3e0005ec06eba950a03a5b40bdd20ba0f558a58d
```
Push branch, set remote as upstream
```
$ git push --set-upstream origin OBGM-58-database-migrations-new
```
Create PR on GitHub.

**Pull request closed without merging**
