### PR TITLE
OBPIH-1110 Minor refactoring of stock movement with shipment present

### PR DESCRIPTION
**Pull request by jmiranda**

### CODE REVIEW

**Comment by jmiranda** [comment]
@pmuchowski I tried refactoring your solution a bit but it looks like the Stock Movement UI does not like if those shipment field (trackingNumber, shipmentType, dateShipped, etc) are set under any condition where status != ISSUED and step number != 5. Is there some way around that? Can you show me the code that checks the initial stock movement read response and then issues another GET for the step 5 response?

**Comment by jmiranda** [comment]
Actually, it's a javascript error that we're only seeing because the `trackingNumber` field is available and the getShipmentMethod() is expecting there to be a `stockList` as well.
```
Uncaught TypeError: Cannot read property 'name' of undefined
```
Code:
```key: "getShipmentName",
            value: function() {
                if (this.state.values.trackingNumber) {
                    var e = this.state.values
                      , t = e.origin
                      , n = e.destination
                      , r = e.dateRequested
                      , o = e.stockList
                      , i = e.trackingNumber
                      , a = e.description
                      , s = o.name ? o.name + "." : ""
                      , u = (0,
                    m.default)(r, "MM/DD/YYYY").format("DDMMMYYYY");
                    return (t.name + "." + n.name + "." + u + "." + s + i + "." + a).replace(/ /gi, "")
                }
                return this.state.values.shipmentName
            }```

**Comment by jmiranda** [comment]
@pmuchowski Alright, should be fixed. Let me know if that fix look ok to you?

**Comment by pmuchowski** [comment]
@jmiranda the actual reason why I added those fields only when status is ISSUED is that the "Ship Date" and "Shipment Type" are prepopulated on the backend when you go to step 5 and I did not wanted those fields to be filled in the form on UI. I'm not sure if this will be an issue, if not it's fine by me.

**Comment by jmiranda** [comment]
Thanks @pmuchowski. That was a good reason to do that. I told Jesse that we might need to prepopulate those field so I'm ok with it. If she doesn't like it I'll figure out another solution.

**Pull request merged**
