### PR TITLE
OBPIH-3700 Fix GL account validation

### PR DESCRIPTION
**Pull request by DominikaHatala**

### CODE REVIEW

**Review by awalkowiak — APPROVED** [review]

**Review by jmiranda — COMMENTED** [review]
@DominikaHatala I'm confused. How does this fix the issue? And shouldn't the validation happen on the controller / services when we try to save the product?

**Comment by DominikaHatala** [comment]
@jmiranda It was broken after the refactor of edit page. This is frontend validation and showing "Required" error next to the field. This validation is implemented in edit.gsp and while refactoring you moved hidden field "isAccountingRequired" to the new file and it was not working anymore.

**Comment by jmiranda** [comment]
@DominikaHatala Oh because the validation code is in edit.gsp. Weird. So if we didn't do this, then the other solution would have been to use live query to get the attributes from the form. But since the form doesn't actually need these values the proposed solution will work fine.

**Review by jmiranda — APPROVED** [review]

**Review by jmiranda — CHANGES_REQUESTED** [review]
But you're rendering the hidden field in the head of the page and it probably needs to be in the body, right?

**Comment by DominikaHatala** [comment]
@jmiranda You're right, it's better when it's in the body although it also works when it's in head.

**Pull request merged**
