### PR TITLE
Merge release-0.8.0 changes to develop

### PR DESCRIPTION
**Pull request by pmuchowski**

### CODE REVIEW

**Comment by jmiranda** [comment]
@pmuchowski Also, we might have a few more changes to include in this merge prior to the release being finalized tomorrow. Would you suggest merging release-0.8.0 into this branch again or should we just merge this and create a new backmerge branch to include those other changes?

**Comment by pmuchowski** [comment]
@jmiranda I don't used merge
git fetch origin
git checkout origin/release-0.8.0
git checkout -b merge-release-to-develop
git rebase origin/develop
<fix merge conflicts>
git push origin merge-release-to-develop

**Comment by jmiranda** [comment]
@pmuchowski Yes, that's correct.

**Comment by jmiranda** [comment]
@pmuchowski When you get a chance can you create another merge from release to develop PR just to get any recent merges. After having a conversation with Jesse, it seems we might do away with the release branch as it's causing too much confusion with respect to which tickets are in/out of the release. We'll discuss on the call on Monday.

**Pull request merged**
