### PR TITLE
OBPIH-2534 Apply color of item search to react pages

### PR DESCRIPTION
**Pull request by DominikaHatala**

### CODE REVIEW

**Comment by jmiranda** [comment]
@DominikaHatala Is this the ticket you were referring to on the standup re: tests not passing? If so do you need me to look into those test failures or are you still investigating?

**Comment by DominikaHatala** [comment]
@jmiranda Yes, I was referring to this ticket. That would be great if you find some time to take a look at those fest failures.

**Comment by awalkowiak** [comment]
@jmiranda @DominikaHatala I found the issue. Unit tests had a problem with this namedQuery:
https://github.com/openboxes/openboxes/blob/OBPIH-2534/grails-app/domain/org/pih/warehouse/product/ProductCatalog.groovy#L36
Temporary I replaced it with this change, https://github.com/openboxes/openboxes/pull/1653/commits/201ca5e00f40c21aa44861f6b42e06e1a1512ce9, but I am not sure about that one. Probably a better approach would be mocking.

**Comment by jmiranda** [comment]
@awalkowiak I can't get it to fail with the previous changes so I don't think we need to look into this any further right now.

**Pull request merged**
